import Link from "next/link";
import { listDailyPlans } from "@/lib/cusoos";

export const dynamic = "force-dynamic";

export default async function DailyIndexPage() {
  const dates = await listDailyPlans();

  return (
    <div className="space-y-8">
      <div className="space-y-2">
        <div className="font-mono text-[11px] tracking-[0.2em] text-[var(--color-bat)]">
          // DAILY // LOG
        </div>
        <h1 className="text-3xl font-semibold tracking-tight text-white">
          Daily plans
        </h1>
        <p className="text-sm text-[var(--color-muted)]">
          {dates.length} plan{dates.length === 1 ? "" : "s"} on file. Generated by{" "}
          <code className="text-[var(--color-bat)]">/plan</code> in Claude Code.
        </p>
      </div>

      {dates.length === 0 ? (
        <p className="text-sm italic text-[var(--color-dim)]">No plans yet.</p>
      ) : (
        <ul className="bat-panel divide-y divide-[var(--color-line)]">
          {dates.map((date) => (
            <li key={date}>
              <Link
                href={`/daily/${date}`}
                className="row-hover flex items-center justify-between px-4 py-3 text-[13px]"
              >
                <span className="font-mono text-white">{date}</span>
                <span className="font-mono text-[10px] tracking-wider text-[var(--color-muted)] uppercase">
                  {formatRelative(date)}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function formatRelative(iso: string): string {
  const d = new Date(iso + "T12:00:00");
  const now = new Date();
  const diffDays = Math.floor(
    (now.getTime() - d.getTime()) / (1000 * 60 * 60 * 24),
  );
  if (diffDays === 0) return "today";
  if (diffDays === 1) return "yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  return d.toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}
